server{
    listen 80;
    
    #API calls -> backend container (by compose service name)
    location /recruits{
        proxy_pass http://backend:8081;
    }

    # the SPA itself
    location /{
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}