package io.github.jamesg1996.cfbrecruiter.domain;

public enum MotivationCategory {
    ACADEMIC_PRESTIGE,
    ATHLETIC_FACILITIES,
    BRAND_EXPOSURE,
    CAMPUS_LIFESTYLE,
    CHAMPIONSHIP_CONTENDER,
    COACH_PRESTIGE,
    COACH_STABILITY,
    CONFERENCE_PRESTIGE,
    PLAYING_STYLE,
    PLAYING_TIME,
    PRO_POTENTIAL,
    PROGRAM_TRADITION,
    PROXIMITY_TO_HOME,
    STADIUM_ATMOSPHERE
}
