CREATE TABLE pitch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL unique
);

CREATE TABLE pitch_motivation (
    pitch_id BIGINT NOT NULL REFERENCES pitch(id) ON DELETE CASCADE,
    category VARCHAR(255) NOT NULL,
    PRIMARY KEY (pitch_id, category)
);