CREATE TABLE recruit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE recruit_motivation (
    recruit_id BIGINT NOT NULL REFERENCES recruit(id) ON DELETE CASCADE,
    category VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (recruit_id, category)
);